### ISSUE TITLE
Fastboot with Ember 2.11: EventDispatcher should never be instantiated in fastboot mode.

### ISSUE THREAD

**Issue by kpfefferle** [ronco/ember-cli-head#18]
Steps to reproduce (using Ember CLI 2.11):

```
ember new fastboot-test
cd fastboot-test
ember install ember-cli-fastboot@1.0.0-beta.13
ember install ember-cli-meta-tags
ember fastboot
```

Upon visiting `localhost:3000` in browser, the following error is displayed:

```
Unknown Error: Error: Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
    at assert (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:16253:13)
    at Object.assert (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:27925:34)
    at Class.init (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:52253:19)
    at Class.superWrapper [as init] (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:50979:22)
    at new Class (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:46671:17)
    at Function._ClassMixinProps.create (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:46859:12)
    at instantiate (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:12101:23)
    at lookup (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:11938:17)
    at Object.lookup (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:11857:14)
    at Class.lookup (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:43117:33)
    at /Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:17904:59
    at Class.init (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:17914:9)
    at Class.superWrapper [as init] (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:50979:22)
    at new Class (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:46671:17)
    at Function._ClassMixinProps.create (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:46859:12)
    at Object.initialize (/Users/kevin/code/fastboot-test/dist/fastboot/fastboot-test.js:328:38)
    at /Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:15115:21
    at Vertices.each (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:13180:13)
    at Vertices.topsort (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:13147:14)
    at DAG.topsort (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:13092:24)
    at Class._runInitializer (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:15130:13)
    at Class.runInstanceInitializers (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:15113:12)
    at Class._bootSync (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:13398:24)
    at /Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:14798:30
    at initializePromise (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:69131:7)
    at new Promise (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:69619:33)
    at Class.boot (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:14797:27)
    at /Users/kevin/code/fastboot-test/node_modules/fastboot/dist/cjs/ember-app.js:235:25
    at tryCatch (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:69081:14)
    at invokeCallback (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:69096:15)
    at publish (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:69064:9)
    at /Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:48967:16
    at invokeWithOnError (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:10898:16)
    at Object.flush (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:10957:9)
    at Object.flush (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:11081:15)
    at Object.end (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:11151:23)
    at Timeout._onTimeout (/Users/kevin/code/fastboot-test/dist/fastboot/vendor.js:11717:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by kpfefferle** [comment]
This seems to be resolved now with a clean reinstall of all upstream dependencies ¯\_(ツ)_/¯
